title: Marc Palumbo
logo: assets/headshot.jpg
description: Passionate about Data | SQL, Python, Tableau | Seeking Data Analyst Position <br> **Social Media Profiles** <br> [GitHub Profile](https://github.com/marcpalumbo) <br> [LinkedIn Profile](https://www.linkedin.com/in/marcpalumbo53/)
show_downloads: false
theme: jekyll-theme-minimal
